### ISSUE TITLE
加载动画后无法继续

### ISSUE THREAD

**Issue by meta-boy** [jinyaoMa/hexo-theme-mustom#2]
加载后，安装说明不清楚，但会卡在加载动画中。

**Comment by jinyaoMa** [comment]
你这问题我查了下是因为extension部分，[我的网站](//ma-jinyao.cn)左下角的功能，没找到内容，404时AJAX里传参部分出了错。
这个问题我也刚发现，主要是我没测试过AJAX出错的情况。这内容添加越来越多，我写个[我的网站](//ma-jinyao.cn)目录结构的文章出来解释一下吧。

**Comment by meta-boy** [comment]
感谢你的快速回复！请编写安装的分步指南

**Comment by jinyaoMa** [comment]
[Hexo主题Mustom使用指南](//ma-jinyao.cn/posts/49651/)

**Comment by meta-boy** [comment]
thank you
