### ISSUE TITLE
请问头像下面的名字怎么改？

### ISSUE THREAD

**Issue by lisuqing2020** [jinyaoMa/hexo-theme-mustom#3]
还有名字下面的我只想安静的做笔记是在哪改的？我在config.yml里面没有找到相关的配置？

**Comment by jinyaoMa** [comment]
在主题 `source/asset/lang/zh-cn.yml` 里面改

**Comment by lisuqing2020** [comment]
> 在主题 `source/asset/lang/zh-cn.yml` 里面改

谢谢，问题已经解决了- …… -
