### ISSUE TITLE
主题真丑...

### ISSUE THREAD

**Issue by zhepama** [jinyaoMa/hexo-theme-mustom#7]
主题真丑...

**Comment by jinyaoMa** [comment]
你说说哪里不好，我把版本倒回去看看，先把不好的地方去掉怎样，你觉得怎样？

**Comment by zhepama** [comment]
1. 首先博客三栏设计就很诡异,信息量太多
2. 颜色搭配黑色对比度太明显,白色就整个白拉拉一片

你不用改,只是我个人不喜欢而已..
也许其他人会喜欢

**Comment by jinyaoMa** [comment]
哦哦，那这个 issue 就留着水贴吧。
@zhepama 
你说的第一点信息量太多是刚开始设计时就注定的问题了，因为我就是要弄三栏的
你说的第二点我就要请教一下了，我很不好意思的说我没看懂，我应该怎么改才能改善这一点？虽然 hexo 这个主题我个人是不想弄了，但是我 vuepress 的主题是搬运的 hexo 的款式。这颜色是要怎么个选法比较好？请教一下
